#!/usr/bin/env python3
"""
Generate CK metrics for Java repositories.

This script:
1. Reads repositories from the CSV generated by 01-fetch-github-data.py
2. Clones repositories (configurable protocol with fallback)
3. Runs CK metrics analysis in parallel (3 repos at a time)
4. Exports metrics to data/ck/{repoName}/ckMetrics.csv
5. Updates the CSV with ckMetricsGenerated status
"""

import argparse
import csv
import os
import shutil
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Dict, List, Optional

DEFAULT_INPUT_CSV = "data/repositories.csv"
DEFAULT_PARALLEL_JOBS = 3
DEFAULT_CK_JAR_PATH = "source-code-ck/ck/target/ck-0.7.1-SNAPSHOT-jar-with-dependencies.jar"
DEFAULT_JVM_MEMORY = "2g"
DEFAULT_MAX_FILES_PER_PARTITION = 500
TEMP_CLONE_DIR = "/tmp/ck-analysis"
DEFAULT_CLONE_TIMEOUT = 900
DEFAULT_CLONE_RETRIES = 1
DEFAULT_CK_TIMEOUT = 0


def ensure_ck_built(ck_path: Path) -> Path:
    """
    Ensure CK tool is built and return path to JAR.
    
    Args:
        ck_path: Path to CK tool directory
    
    Returns:
        Path to CK JAR file
    
    Raises:
        RuntimeError: If CK build fails
    """
    ck_dir = ck_path.parent.parent / "source-code-ck" / "ck"
    
    if not ck_dir.exists():
        raise RuntimeError(
            f"CK tool not found at {ck_dir}. "
            "Please ensure the CK submodule is initialized: git submodule update --init"
        )
    
    # Look for existing JAR
    target_dir = ck_dir / "target"
    if target_dir.exists():
        jars = list(target_dir.glob("ck-*-jar-with-dependencies.jar"))
        if jars:
            print(f"Found CK JAR: {jars[0]}", file=sys.stderr)
            return jars[0]
    
    # Build CK if JAR not found
    print("Building CK tool...", file=sys.stderr)
    try:
        subprocess.run(
            ["./mvnw", "clean", "package", "-DskipTests"],
            cwd=ck_dir,
            check=True,
            capture_output=True,
            text=True
        )
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Failed to build CK tool: {e.stderr}") from e
    
    # Find the built JAR
    jars = list(target_dir.glob("ck-*-jar-with-dependencies.jar"))
    if not jars:
        raise RuntimeError("CK JAR not found after build")
    
    print(f"CK tool built successfully: {jars[0]}", file=sys.stderr)
    return jars[0]


def _count_csv_data_rows(csv_file: Path) -> int:
    if not csv_file.exists():
        return 0
    with open(csv_file, "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        return max(sum(1 for _ in reader) - 1, 0)


def _build_git_url(repo_url: str, protocol: str) -> Optional[str]:
    if protocol == "http":
        return repo_url + ".git"
    if protocol == "ssh":
        parts = repo_url.replace("https://github.com/", "").split("/")
        if len(parts) != 2:
            return None
        owner, repo = parts
        return f"git@github.com:{owner}/{repo}.git"
    return None


def _has_valid_ck_metrics(output_dir: Path) -> bool:
    return _count_csv_data_rows(output_dir / "ckMetrics.csv") > 0


def clone_repository(
    repo_url: str,
    clone_dir: Path,
    clone_protocol: str = "auto",
    clone_timeout: int = DEFAULT_CLONE_TIMEOUT,
    clone_retries: int = DEFAULT_CLONE_RETRIES,
) -> bool:
    """
    Clone a repository using SSH or HTTP.
    
    Args:
        repo_url: GitHub repository URL (https://github.com/owner/repo)
        clone_dir: Directory to clone into
        clone_protocol: http, ssh, or auto
        clone_timeout: git clone timeout in seconds
        clone_retries: retries per protocol

    Returns:
        True if successful, False otherwise
    """
    if clone_protocol == "http":
        protocols = ["http", "ssh"]
    elif clone_protocol == "ssh":
        protocols = ["ssh", "http"]
    else:
        protocols = ["http", "ssh"]

    for protocol in protocols:
        git_url = _build_git_url(repo_url, protocol)
        if git_url is None:
            continue

        attempts = max(clone_retries, 0) + 1
        for attempt in range(1, attempts + 1):
            if clone_dir.exists():
                shutil.rmtree(clone_dir, ignore_errors=True)

            try:
                subprocess.run(
                    ["git", "clone", "--depth", "1", git_url, str(clone_dir)],
                    check=True,
                    capture_output=True,
                    text=True,
                    timeout=clone_timeout,
                )
                return True
            except subprocess.TimeoutExpired:
                print(
                    f"Clone timeout ({clone_timeout}s) for {repo_url} via {protocol} "
                    f"(attempt {attempt}/{attempts})",
                    file=sys.stderr,
                )
            except subprocess.CalledProcessError as e:
                stderr = (e.stderr or "").strip().splitlines()
                preview = stderr[0] if stderr else str(e)
                print(
                    f"Clone failed for {repo_url} via {protocol} "
                    f"(attempt {attempt}/{attempts}): {preview}",
                    file=sys.stderr,
                )

    return False


def run_ck_analysis(
    ck_jar: Path,
    repo_dir: Path,
    output_dir: Path,
    jvm_memory: str = DEFAULT_JVM_MEMORY,
    max_files_per_partition: int = DEFAULT_MAX_FILES_PER_PARTITION,
    ck_timeout: int = DEFAULT_CK_TIMEOUT,
) -> bool:
    """
    Run CK metrics analysis on a repository.
    
    Args:
        ck_jar: Path to CK JAR file
        repo_dir: Path to cloned repository
        output_dir: Directory to save metrics CSV
        jvm_memory: JVM max heap size (e.g. '2g')
        max_files_per_partition: CK partition size to avoid OOM on large repos
    
    Returns:
        True if successful, False otherwise
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    
    try:
        # CK usage: java -jar ck.jar <project-dir> <use-jars> <max-files-per-partition> <use-variables-name> <output-dir>
        result = subprocess.run(
            [
                "java",
                f"-Xmx{jvm_memory}",
                "-Xms512m",
                "-jar", str(ck_jar),
                str(repo_dir),                    # project directory
                "true",                           # use jars
                str(max_files_per_partition),     # max files per partition
                "false",                          # use variables name
                str(output_dir),                  # output directory
            ],
            check=True,
            capture_output=True,
            text=True,
            timeout=ck_timeout if ck_timeout > 0 else None,
        )
        
        # Check if metrics file was generated
        class_file = output_dir / "class.csv"
        metrics_file = output_dir / "ckMetrics.csv"
        if class_file.exists():
            class_file.replace(metrics_file)

        if not metrics_file.exists():
            print(f"CK metrics file not generated for {repo_dir.name}", file=sys.stderr)
            if result.stderr:
                print(f"CK stderr:\n{result.stderr[:1000]}", file=sys.stderr)
            return False

        if _count_csv_data_rows(metrics_file) == 0:
            print(f"CK metrics empty for {repo_dir.name}", file=sys.stderr)
            return False

        return True

    except subprocess.CalledProcessError as e:
        print(f"Failed to run CK analysis on {repo_dir.name}: exit {e.returncode}", file=sys.stderr)
        if e.stderr:
            lines = e.stderr.strip().splitlines()
            preview = "\n".join(lines[:30])
            print(f"CK stderr (first 30 lines):\n{preview}", file=sys.stderr)
        return False
    except subprocess.TimeoutExpired as e:
        print(
            f"Failed to run CK analysis on {repo_dir.name}: timed out after {e.timeout}s",
            file=sys.stderr,
        )
        return False


def process_repository(
    repo: Dict,
    ck_jar: Path,
    clone_protocol: str,
    temp_dir: Path,
    data_dir: Path,
    jvm_memory: str = DEFAULT_JVM_MEMORY,
    max_files_per_partition: int = DEFAULT_MAX_FILES_PER_PARTITION,
    clone_timeout: int = DEFAULT_CLONE_TIMEOUT,
    clone_retries: int = DEFAULT_CLONE_RETRIES,
    ck_timeout: int = DEFAULT_CK_TIMEOUT,
) -> Dict:
    """
    Process a single repository: clone, analyze, cleanup.
    
    Args:
        repo: Repository data dictionary
        ck_jar: Path to CK JAR file
        clone_protocol: Clone protocol preference
        temp_dir: Temporary directory for cloning
        data_dir: Base data directory for output
    
    Returns:
        Updated repository dictionary with ckMetricsGenerated status
    """
    repo_name = repo["nameWithOwner"]
    repo_url = repo["url"]
    safe_name = repo_name.replace("/", "_")
    clone_dir = temp_dir / safe_name
    output_dir = data_dir / "ck" / safe_name
    
    print(f"Processing: {repo_name}", file=sys.stderr)
    
    # Skip if already processed and metrics file is non-empty
    if repo.get("ckMetricsGenerated", "").lower() == "true" and _has_valid_ck_metrics(output_dir):
        print(f"Skipping {repo_name}: already processed", file=sys.stderr)
        return repo
    
    try:
        # Clone repository
        if not clone_repository(
            repo_url,
            clone_dir,
            clone_protocol=clone_protocol,
            clone_timeout=clone_timeout,
            clone_retries=clone_retries,
        ):
            repo["ckMetricsGenerated"] = "false"
            return repo
        
        # Run CK analysis
        if run_ck_analysis(
            ck_jar,
            clone_dir,
            output_dir,
            jvm_memory,
            max_files_per_partition,
            ck_timeout=ck_timeout,
        ):
            repo["ckMetricsGenerated"] = "true"
            print(f"✓ Completed: {repo_name}", file=sys.stderr)
        else:
            repo["ckMetricsGenerated"] = "false"
            print(f"✗ Failed: {repo_name}", file=sys.stderr)
    
    finally:
        # Cleanup cloned repository
        if clone_dir.exists():
            shutil.rmtree(clone_dir, ignore_errors=True)
    
    return repo


def load_repositories(csv_file: Path) -> List[Dict]:
    """Load repositories from CSV file."""
    if not csv_file.exists():
        raise FileNotFoundError(f"CSV file not found: {csv_file}")
    
    repos = []
    with open(csv_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            repos.append(row)
    
    return repos


def save_repositories(csv_file: Path, repos: List[Dict]):
    """Save repositories to CSV file."""
    if not repos:
        return
    
    # Ensure ckMetricsGenerated column exists
    fieldnames = list(repos[0].keys())
    if "ckMetricsGenerated" not in fieldnames:
        fieldnames.append("ckMetricsGenerated")
    
    with open(csv_file, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(repos)


def main():
    parser = argparse.ArgumentParser(
        description="Generate CK metrics for Java repositories"
    )
    parser.add_argument(
        "--input",
        type=str,
        default=DEFAULT_INPUT_CSV,
        help=f"Input CSV file with repositories (default: {DEFAULT_INPUT_CSV})"
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Number of repositories to analyze (default: all pending)"
    )
    parser.add_argument(
        "--parallel",
        type=int,
        default=DEFAULT_PARALLEL_JOBS,
        help=f"Number of parallel jobs (default: {DEFAULT_PARALLEL_JOBS})"
    )
    parser.add_argument(
        "--clone-protocol",
        type=str,
        choices=["auto", "http", "ssh"],
        default="auto",
        help="Clone protocol priority (default: auto=HTTPS then SSH)"
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-analyze repositories even if already processed"
    )
    parser.add_argument(
        "--jvm-memory",
        type=str,
        default=DEFAULT_JVM_MEMORY,
        help=f"JVM max heap per CK instance (default: {DEFAULT_JVM_MEMORY}). Example: 4g, 1500m"
    )
    parser.add_argument(
        "--max-files",
        type=int,
        default=DEFAULT_MAX_FILES_PER_PARTITION,
        help=f"CK max files per partition, reduces OOM on large repos (default: {DEFAULT_MAX_FILES_PER_PARTITION}, 0=no limit)"
    )
    parser.add_argument(
        "--skip-failed",
        action="store_true",
        help="Skip repositories previously marked as failed (ckMetricsGenerated=false)"
    )
    parser.add_argument(
        "--clone-timeout",
        type=int,
        default=DEFAULT_CLONE_TIMEOUT,
        help=f"git clone timeout in seconds (default: {DEFAULT_CLONE_TIMEOUT})",
    )
    parser.add_argument(
        "--clone-retries",
        type=int,
        default=DEFAULT_CLONE_RETRIES,
        help=f"Retries per clone protocol (default: {DEFAULT_CLONE_RETRIES})",
    )
    parser.add_argument(
        "--ck-timeout",
        type=int,
        default=DEFAULT_CK_TIMEOUT,
        help=f"CK timeout in seconds, 0 disables timeout (default: {DEFAULT_CK_TIMEOUT})",
    )
    
    args = parser.parse_args()
    
    # Setup paths
    script_dir = Path(__file__).parent.parent
    input_csv = Path(args.input)
    if not input_csv.is_absolute():
        input_csv = script_dir / input_csv
    
    data_dir = script_dir / "data"
    temp_dir = Path(TEMP_CLONE_DIR)
    temp_dir.mkdir(parents=True, exist_ok=True)
    
    # Ensure CK is built
    ck_jar = ensure_ck_built(Path(__file__))
    
    # Load repositories
    print(f"Loading repositories from {input_csv}", file=sys.stderr)
    repos = load_repositories(input_csv)
    
    # Filter repositories to process
    if args.force:
        # Reset ckMetricsGenerated for all repos
        for repo in repos:
            repo["ckMetricsGenerated"] = "false"
    
    # Get pending repositories
    def is_valid_processed(repo: Dict) -> bool:
        status = repo.get("ckMetricsGenerated", "").lower()
        if status != "true":
            return False
        safe_name = repo["nameWithOwner"].replace("/", "_")
        output_dir = data_dir / "ck" / safe_name
        return _has_valid_ck_metrics(output_dir)

    if args.skip_failed:
        pending_repos = [
            repo for repo in repos
            if repo.get("ckMetricsGenerated", "").lower() != "false" and not is_valid_processed(repo)
        ]
    else:
        pending_repos = [
            repo for repo in repos
            if not is_valid_processed(repo)
        ]
    
    if not pending_repos:
        print("No repositories to process", file=sys.stderr)
        return
    
    # Apply limit
    if args.limit:
        pending_repos = pending_repos[:args.limit]
    
    print(f"Processing {len(pending_repos)} repositories with {args.parallel} parallel jobs", file=sys.stderr)
    print(f"Clone protocol: {args.clone_protocol}", file=sys.stderr)
    print(f"JVM memory per instance: {args.jvm_memory}  |  max-files-per-partition: {args.max_files}", file=sys.stderr)
    print(
        f"Timeouts: clone={args.clone_timeout}s, ck={'disabled' if args.ck_timeout == 0 else str(args.ck_timeout) + 's'}",
        file=sys.stderr,
    )
    
    # Process repositories in parallel
    processed_repos = []
    with ThreadPoolExecutor(max_workers=args.parallel) as executor:
        futures = {
            executor.submit(
                process_repository,
                repo,
                ck_jar,
                args.clone_protocol,
                temp_dir,
                data_dir,
                args.jvm_memory,
                args.max_files,
                args.clone_timeout,
                args.clone_retries,
                args.ck_timeout,
            ): repo for repo in pending_repos
        }
        
        for future in as_completed(futures):
            try:
                result = future.result()
                processed_repos.append(result)
            except Exception as e:
                repo = futures[future]
                print(f"Exception processing {repo['nameWithOwner']}: {e}", file=sys.stderr)
                repo["ckMetricsGenerated"] = "false"
                processed_repos.append(repo)
    
    # Update original repos list with processed results
    processed_names = {r["nameWithOwner"] for r in processed_repos}
    for i, repo in enumerate(repos):
        if repo["nameWithOwner"] in processed_names:
            repos[i] = next(r for r in processed_repos if r["nameWithOwner"] == repo["nameWithOwner"])
    
    # Save updated CSV
    print(f"Saving results to {input_csv}", file=sys.stderr)
    save_repositories(input_csv, repos)
    
    # Print summary
    successful = sum(1 for r in processed_repos if r.get("ckMetricsGenerated") == "true")
    print(f"\n{'='*60}", file=sys.stderr)
    print(f"Summary:", file=sys.stderr)
    print(f"  Total processed: {len(processed_repos)}", file=sys.stderr)
    print(f"  Successful: {successful}", file=sys.stderr)
    print(f"  Failed: {len(processed_repos) - successful}", file=sys.stderr)
    print(f"{'='*60}", file=sys.stderr)


if __name__ == "__main__":
    main()
