#!/usr/bin/env python3
"""
Generate CK metrics for Java repositories.

This script:
1. Reads repositories from the CSV generated by 01-fetch-github-data.py
2. Clones repositories (SSH by default, HTTP optional)
3. Runs CK metrics analysis in parallel (3 repos at a time)
4. Exports metrics to data/ck/{repoName}/ckMetrics.csv
5. Updates the CSV with ckMetricsGenerated status
"""

import argparse
import csv
import os
import shutil
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Dict, List, Optional

DEFAULT_INPUT_CSV = "data/repositories.csv"
DEFAULT_PARALLEL_JOBS = 10
DEFAULT_CK_JAR_PATH = "source-code-ck/ck/target/ck-0.7.1-SNAPSHOT-jar-with-dependencies.jar"
TEMP_CLONE_DIR = "/tmp/ck-analysis"


def ensure_ck_built(ck_path: Path) -> Path:
    """
    Ensure CK tool is built and return path to JAR.
    
    Args:
        ck_path: Path to CK tool directory
    
    Returns:
        Path to CK JAR file
    
    Raises:
        RuntimeError: If CK build fails
    """
    ck_dir = ck_path.parent.parent / "source-code-ck" / "ck"
    
    if not ck_dir.exists():
        raise RuntimeError(
            f"CK tool not found at {ck_dir}. "
            "Please ensure the CK submodule is initialized: git submodule update --init"
        )
    
    # Look for existing JAR
    target_dir = ck_dir / "target"
    if target_dir.exists():
        jars = list(target_dir.glob("ck-*-jar-with-dependencies.jar"))
        if jars:
            print(f"Found CK JAR: {jars[0]}", file=sys.stderr)
            return jars[0]
    
    # Build CK if JAR not found
    print("Building CK tool...", file=sys.stderr)
    try:
        subprocess.run(
            ["./mvnw", "clean", "package", "-DskipTests"],
            cwd=ck_dir,
            check=True,
            capture_output=True,
            text=True
        )
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Failed to build CK tool: {e.stderr}") from e
    
    # Find the built JAR
    jars = list(target_dir.glob("ck-*-jar-with-dependencies.jar"))
    if not jars:
        raise RuntimeError("CK JAR not found after build")
    
    print(f"CK tool built successfully: {jars[0]}", file=sys.stderr)
    return jars[0]


def clone_repository(repo_url: str, clone_dir: Path, use_http: bool = False) -> bool:
    """
    Clone a repository using SSH or HTTP.
    
    Args:
        repo_url: GitHub repository URL (https://github.com/owner/repo)
        clone_dir: Directory to clone into
        use_http: If True, use HTTPS; otherwise use SSH
    
    Returns:
        True if successful, False otherwise
    """
    # Convert GitHub URL to SSH or keep as HTTPS
    if use_http:
        git_url = repo_url + ".git"
    else:
        # Convert https://github.com/owner/repo to git@github.com:owner/repo.git
        parts = repo_url.replace("https://github.com/", "").split("/")
        if len(parts) != 2:
            print(f"Invalid GitHub URL: {repo_url}", file=sys.stderr)
            return False
        owner, repo = parts
        git_url = f"git@github.com:{owner}/{repo}.git"
    
    try:
        subprocess.run(
            ["git", "clone", "--depth", "1", git_url, str(clone_dir)],
            check=True,
            capture_output=True,
            text=True,
            timeout=600  # 10 minute timeout
        )
        return True
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as e:
        print(f"Failed to clone {repo_url}: {e}", file=sys.stderr)
        return False


def run_ck_analysis(ck_jar: Path, repo_dir: Path, output_dir: Path) -> bool:
    """
    Run CK metrics analysis on a repository.
    
    Args:
        ck_jar: Path to CK JAR file
        repo_dir: Path to cloned repository
        output_dir: Directory to save metrics CSV
    
    Returns:
        True if successful, False otherwise
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    
    try:
        # CK usage: java -jar ck.jar <project-dir> <use-jars> <max-files-per-partition> <use-variables-name> <output-dir>
        subprocess.run(
            [
                "java", "-jar", str(ck_jar),
                str(repo_dir),  # project directory
                "true",         # use jars
                "0",            # max files per partition (0 = no limit)
                "false",        # use variables name
                str(output_dir) # output directory
            ],
            check=True,
            capture_output=True,
            text=True,
            timeout=600  # 10 minute timeout
        )
        
        # Check if metrics file was generated
        metrics_file = output_dir / "class.csv"
        if metrics_file.exists():
            # Rename to ckMetrics.csv
            metrics_file.rename(output_dir / "ckMetrics.csv")
            return True
        else:
            print(f"CK metrics file not generated for {repo_dir.name}", file=sys.stderr)
            return False
            
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as e:
        print(f"Failed to run CK analysis on {repo_dir.name}: {e}", file=sys.stderr)
        return False


def process_repository(
    repo: Dict,
    ck_jar: Path,
    use_http: bool,
    temp_dir: Path,
    data_dir: Path
) -> Dict:
    """
    Process a single repository: clone, analyze, cleanup.
    
    Args:
        repo: Repository data dictionary
        ck_jar: Path to CK JAR file
        use_http: Whether to use HTTP for cloning
        temp_dir: Temporary directory for cloning
        data_dir: Base data directory for output
    
    Returns:
        Updated repository dictionary with ckMetricsGenerated status
    """
    repo_name = repo["nameWithOwner"]
    repo_url = repo["url"]
    
    print(f"Processing: {repo_name}", file=sys.stderr)
    
    # Skip if already processed
    if repo.get("ckMetricsGenerated", "").lower() == "true":
        print(f"Skipping {repo_name}: already processed", file=sys.stderr)
        return repo
    
    # Create unique clone directory
    safe_name = repo_name.replace("/", "_")
    clone_dir = temp_dir / safe_name
    output_dir = data_dir / "ck" / safe_name
    
    try:
        # Clone repository
        if not clone_repository(repo_url, clone_dir, use_http):
            repo["ckMetricsGenerated"] = "false"
            return repo
        
        # Run CK analysis
        if run_ck_analysis(ck_jar, clone_dir, output_dir):
            repo["ckMetricsGenerated"] = "true"
            print(f"✓ Completed: {repo_name}", file=sys.stderr)
        else:
            repo["ckMetricsGenerated"] = "false"
            print(f"✗ Failed: {repo_name}", file=sys.stderr)
    
    finally:
        # Cleanup cloned repository
        if clone_dir.exists():
            shutil.rmtree(clone_dir, ignore_errors=True)
    
    return repo


def load_repositories(csv_file: Path) -> List[Dict]:
    """Load repositories from CSV file."""
    if not csv_file.exists():
        raise FileNotFoundError(f"CSV file not found: {csv_file}")
    
    repos = []
    with open(csv_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            repos.append(row)
    
    return repos


def save_repositories(csv_file: Path, repos: List[Dict]):
    """Save repositories to CSV file."""
    if not repos:
        return
    
    # Ensure ckMetricsGenerated column exists
    fieldnames = list(repos[0].keys())
    if "ckMetricsGenerated" not in fieldnames:
        fieldnames.append("ckMetricsGenerated")
    
    with open(csv_file, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(repos)


def main():
    parser = argparse.ArgumentParser(
        description="Generate CK metrics for Java repositories"
    )
    parser.add_argument(
        "--input",
        type=str,
        default=DEFAULT_INPUT_CSV,
        help=f"Input CSV file with repositories (default: {DEFAULT_INPUT_CSV})"
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Number of repositories to analyze (default: all pending)"
    )
    parser.add_argument(
        "--parallel",
        type=int,
        default=DEFAULT_PARALLEL_JOBS,
        help=f"Number of parallel jobs (default: {DEFAULT_PARALLEL_JOBS})"
    )
    parser.add_argument(
        "--use-http",
        action="store_true",
        help="Use HTTPS for cloning instead of SSH (default: SSH)"
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-analyze repositories even if already processed"
    )
    
    args = parser.parse_args()
    
    # Setup paths
    script_dir = Path(__file__).parent.parent
    input_csv = Path(args.input)
    if not input_csv.is_absolute():
        input_csv = script_dir / input_csv
    
    data_dir = script_dir / "data"
    temp_dir = Path(TEMP_CLONE_DIR)
    temp_dir.mkdir(parents=True, exist_ok=True)
    
    # Ensure CK is built
    ck_jar = ensure_ck_built(Path(__file__))
    
    # Load repositories
    print(f"Loading repositories from {input_csv}", file=sys.stderr)
    repos = load_repositories(input_csv)
    
    # Filter repositories to process
    if args.force:
        # Reset ckMetricsGenerated for all repos
        for repo in repos:
            repo["ckMetricsGenerated"] = "false"
    
    # Get pending repositories
    pending_repos = [
        repo for repo in repos
        if repo.get("ckMetricsGenerated", "").lower() != "true"
    ]
    
    if not pending_repos:
        print("No repositories to process", file=sys.stderr)
        return
    
    # Apply limit
    if args.limit:
        pending_repos = pending_repos[:args.limit]
    
    print(f"Processing {len(pending_repos)} repositories with {args.parallel} parallel jobs", file=sys.stderr)
    print(f"Clone method: {'HTTPS' if args.use_http else 'SSH'}", file=sys.stderr)
    
    # Process repositories in parallel
    processed_repos = []
    with ThreadPoolExecutor(max_workers=args.parallel) as executor:
        futures = {
            executor.submit(
                process_repository,
                repo,
                ck_jar,
                args.use_http,
                temp_dir,
                data_dir
            ): repo for repo in pending_repos
        }
        
        for future in as_completed(futures):
            try:
                result = future.result()
                processed_repos.append(result)
            except Exception as e:
                repo = futures[future]
                print(f"Exception processing {repo['nameWithOwner']}: {e}", file=sys.stderr)
                repo["ckMetricsGenerated"] = "false"
                processed_repos.append(repo)
    
    # Update original repos list with processed results
    processed_names = {r["nameWithOwner"] for r in processed_repos}
    for i, repo in enumerate(repos):
        if repo["nameWithOwner"] in processed_names:
            repos[i] = next(r for r in processed_repos if r["nameWithOwner"] == repo["nameWithOwner"])
    
    # Save updated CSV
    print(f"Saving results to {input_csv}", file=sys.stderr)
    save_repositories(input_csv, repos)
    
    # Print summary
    successful = sum(1 for r in processed_repos if r.get("ckMetricsGenerated") == "true")
    print(f"\n{'='*60}", file=sys.stderr)
    print(f"Summary:", file=sys.stderr)
    print(f"  Total processed: {len(processed_repos)}", file=sys.stderr)
    print(f"  Successful: {successful}", file=sys.stderr)
    print(f"  Failed: {len(processed_repos) - successful}", file=sys.stderr)
    print(f"{'='*60}", file=sys.stderr)


if __name__ == "__main__":
    main()
